### ISSUE TITLE
Broken stackname validation for dynamic names

### ISSUE THREAD

**Issue by tdjones** [honarpour/serverless-export-outputs#4]
Service name provided via variable do not pass validation
Using: `service: ${file(./configvars.js):variables.service}` causes the following output at the end of the deploy sequence.

`{ ServerlessError: 1 validation error detected: Value '${file(./configvars.js):variables.service}-dev' at 'stackName' failed to satisfy constraint: Member must satisfy regular expression pattern: [a-zA-Z][-a-zA-Z0-9]*|arn:[-a-zA-Z0-9:/._+]*
    at promise.catch.err (/Users/account/.nvm/versions/node/v10.16.0/lib/node_modules/serverless/lib/plugins/aws/provider/awsProvider.js:317:27)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  statusCode: 400,
  providerError:
   { ValidationError: 1 validation error detected: Value '${file(./configvars.js):variables.service}-dev' at 'stackName' failed to satisfy constraint: Member must satisfy regular expression pattern: [a-zA-Z][-a-zA-Z0-9]*|arn:[-a-zA-Z0-9:/._+]*
       at Request.extractError (/Users/account/.nvm/versions/node/v10.16.0/lib/node_modules/serverless/node_modules/aws-sdk/lib/protocol/query.js:50:29)
       at Request.callListeners (/Users/account/.nvm/versions/node/v10.16.0/lib/node_modules/serverless/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
       at Request.emit (/Users/account/.nvm/versions/node/v10.16.0/lib/node_modules/serverless/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
       .
       .
       .
       at IncomingMessage.onEnd (/Users/account/.nvm/versions/node/v10.16.0/lib/node_modules/serverless/node_modules/aws-sdk/lib/event_listeners.js:307:13)
       at IncomingMessage.emit (events.js:203:15)
       at IncomingMessage.EventEmitter.emit (domain.js:448:20)
       at endReadableNT (_stream_readable.js:1129:12)
       at process._tickCallback (internal/process/next_tick.js:63:19)
     message:
      '1 validation error detected: Value \'${file(./configvars.js):variables.service}-dev\' at \'stackName\' failed to satisfy constraint: Member must satisfy regular expression pattern: [a-zA-Z][-a-zA-Z0-9]*|arn:[-a-zA-Z0-9:/._+]*',
     code: 'ValidationError',
     time: 2019-12-01T04:20:56.388Z,
     requestId: 'f48519f6-5400-4b4d-905b-7b86802df89a',
     statusCode: 400,
     retryable: false,
     retryDelay: 96.65996793924766 } }
Serverless: Run the "serverless" command to setup monitoring, troubleshooting and testing.`

**Comment by gavinsharp** [comment]
This seems to be a fundamental issue with serverless variable resolution. Related issues:
https://github.com/serverless/serverless/issues/7895
https://github.com/serverless/serverless/issues/7207

**Comment by tdjones** [comment]
Solution was to update the global serverless cli. Seems to have been a conflict between it and the local install.
